export const CHANGE_PROVINCES="CHANGE_PROVINCES";
export const CHANGE_CITIES="CHANGE_CITIES";
export const CHANGE_DISTRICTS="CHANGE_DISTRICTS";
export const HAS_CHANGE_PROVINCES="HAS_CHANGE_PROVINCES";
export const HAS_CHANGE_CITIES="HAS_CHANGE_CITIES";
export const HAS_CHANGE_DISTRICTS="HAS_CHANGE_DISTRICTS";
